config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
devise_scope :user do
  root "items#index"
end


  resources :charges
  resources :items
  resources :carts
  post "/add_item" => "carts#add_item"
  post "/delete_item" => "carts#delete_item"
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user! 
	def new
    @cart = Cart.find_by_id(session[:cart_id])
    @temp = @cart.totalcost * 100
    @amount = @temp.to_i
	end

	def create
    @cart = Cart.find_by_id(session[:cart_id])
    str1 = ''
    @cart.items.each do |drinks|
      str1 += "item: #{drinks.name}\n"
      str1 += "price: #{drinks.price.to_s}\n"
      str1 += "quantity: #{drinks.quantity.to_s}\n"
      str1 += "totalcost: #{drinks.totalprice.to_s}\n"
    end
  	# Amount in cents
  	@temp = @cart.totalcost * 100
    @amount = @temp.to_i
  	customer = Stripe::Customer.create(
    	:email => params[:stripeEmail],
    	:source  => params[:stripeToken]
  	)

  	charge = Stripe::Charge.create(
    	:customer    => customer.id,
    	:amount      => @amount,
    	:description => "#{str1}",
    	:currency    => 'usd'
  	)
    
	rescue Stripe::CardError => e
  	flash[:error] = e.message
  	redirect_to new_charge_path
	end
 

  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Shop-Energy</title>
        <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
    <div><%= flash[:message] if flash[:message] %></div>
<nav class="navbar">
        <ul>
        <li> <%= link_to "Shop", items_path, class: "navList" %></li>
        <% if !user_signed_in? %>
            <li><%= link_to "Register", new_user_registration_path, class: "navList" %></li>
            <li><%= link_to "Login", new_user_session_path, class: "navList"%></li>
        <% end %>
             <li><%= link_to "Cart", cart_path(session[:cart_id]), class: "navList" %></li>

        <% if user_signed_in? %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navList"%></li>
        <% end %>
        </ul>
</nav>

<h2>Thanks, you paid <strong> $<%=@cart.totalcost%> </strong>!</h2>
<h3>Heres your receipt, items will be delivered in 5-7 business days. Keep this for your records</h3>

<% @cart.items.each do |t| %>
<div class="cart_items">
    <div class="drinkName"><%= t.name %></div><br> price: $<%= t.price %> <br><%= image_tag t.avatar.url(:medium) %><br> quantity: x<%= t.quantity %><br> totalcost: $<%=t.totalprice%> <br>
</div>
<%end %>
<br>
<div>
Amount Paid: $<%= @cart.totalcost %>
 <% @cart.items.delete_all %>
     <% @cart.update(totalcost: 0) %> <br>
<%= link_to "Done", items_path, class: "navList" %> 
</div>  
</body>
</html>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button";
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>";
          data-description="Checkout Cart"
          data-amount= " <%= @cart.totalcost * 100 %> "
          data-locale="auto"
          data-billing-address = "true" 
          data-shipping-address = "true">
          </script>
<% end %>